### ISSUE TITLE
Add Logging Support for API

### ISSUE THREAD

**Issue by tamilselvanid** [addon365/b1ke-sh0wr00m#12]
Investigate and implement Logging support for API.

**Comment by sathishid** [comment]
Logging supported added and it is working in Azure Log.
**Commit Details:**
146141d3424b2071673b5557f4a1a3a2ae4bea81

**Sample Screen Shot:**

![api_log_azure](https://user-images.githubusercontent.com/20131704/47211407-fd2ca100-d3b2-11e8-96e6-c7699eb439ac.png)

**Comment by sathishid** [comment]
Log does not write the data to file properly in azure environment

**Comment by sathishid** [comment]
Implemented File Logging in Azure using Serilog library.

**Commit Details:**
1ad0edbb4e4f34d63c587a393de399336f318bd3

**Comment by sathishid** [comment]
Included the class name in Log,

**Sample Output:**

![image](https://user-images.githubusercontent.com/20131704/50043071-bba73200-0093-11e9-82a9-c9f4791177a5.png)

**Commit Details:**
8068536e0d36ca51b184d8bb8cda5c8a0f5fab9b
