### ISSUE TITLE
Add support for Splash Screen with the Background Process

### ISSUE THREAD

**Issue by tamilselvanid** [addon365/b1ke-sh0wr00m#13]
Following background process need to be run behind Splash Screen.
1. Ensure Internet Connection.
2. Ensure WebService and DB

**Comment by sathishid** [comment]
Feature has been implemented. 
1. Ensured Internet Connection
2. Ensured Rest Server up & Running.
3. **_Disabled the First Channel Exception handling to catch the Server Status._**

Let me know your view on the above highlighted point?
